### ISSUE TITLE
Query about NER dataset

### ISSUE THREAD

**Issue by shariarkhan433** [banglanlp/bnlp-resources#1]
Can you please elaborate which dataset was used for the NER task? TIA

**Comment by firojalam** [comment]
@AridHasan
Did we release this dataset, can you please check? 
I think we can release it if not done.

**Comment by AridHasan** [comment]
@firojalam 
We didn’t release NER dataset due to its licensing.  It’s a proprietary license.

**Comment by shariarkhan433** [comment]
is there any way i can obtain that dataset? i need that for study purpose.
